# Generated by Django 6.0.3 on 2026-03-05 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0038_alter_tbl_booking_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_user',
            name='city_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.tbl_city'),
        ),
    ]
