# Generated by Django 6.0.3 on 2026-03-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0039_tbl_user_city_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_shows',
            name='showdate',
            field=models.DateField(null=True),
        ),
    ]
