# Generated by Django 6.0.3 on 2026-03-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0040_tbl_shows_showdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_review',
            name='review_rating',
            field=models.TextField(null=True),
        ),
    ]
