# Generated by Django 6.0.3 on 2026-03-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0041_tbl_review_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_movie',
            name='movie_genre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tbl_movie',
            name='movie_rating',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tbl_movie',
            name='movie_release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbl_movie',
            name='movie_trailer',
            field=models.FileField(blank=True, null=True, upload_to='Assets/Movies/'),
        ),
        migrations.AlterField(
            model_name='tbl_review',
            name='review_rating',
            field=models.TextField(),
        ),
    ]
