# Generated by Django 6.0.3 on 2026-03-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0042_tbl_movie_movie_genre_tbl_movie_movie_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_movie',
            name='movie_trailer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
