# Generated by Django 6.0.3 on 2026-03-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0043_alter_tbl_movie_movie_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
