# Generated by Django 6.0.2 on 2026-03-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0044_tbl_booking_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_theater',
            name='theater_status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
