# Generated by Django 6.0.2 on 2026-03-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0045_tbl_theater_theater_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_upcomingmovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upmovie_title', models.CharField(max_length=100)),
                ('upmovie_description', models.TextField()),
                ('upmovie_genre', models.CharField(max_length=50)),
                ('upmovie_release_date', models.DateField()),
                ('upmovie_trailer', models.CharField(max_length=255)),
                ('upmovie_poster', models.FileField(upload_to='upcoming/poster/')),
            ],
        ),
    ]
