# Generated by Django 6.0.3 on 2026-03-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0046_tbl_upcomingmovies'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_theater',
            name='theater_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
