# Generated by Django 6.0.3 on 2026-03-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0047_tbl_theater_theater_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_theater',
            name='theater_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
    ]
